Commit from Pycharm

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,14 +34,14 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      # 1. Set up Python
-      - name: 1. Set up Python
+      # (1) - Set up Python
+      - name: (1) - Set up Python
         uses: actions/setup-python@v3
         with:
           python-version: ${{ matrix.python-version }}
 
-      # 2. Compile for All Operating System (Linux, MacOS, Windows) and All Arquitectures (amd64, arm64)
-      - name: 2. Compile for All Operating System (Linux, MacOS, Windows) and All Arquitectures (amd64, arm64)
+      # (2) - Compile for All Operating System (Linux, MacOS, Windows) and All Arquitectures (amd64, arm64)
+      - name: (2) - Compile for All Operating System (Linux, MacOS, Windows) and All Arquitectures (amd64, arm64)
         run: |
           echo "::group::Compile for ${{ matrix.os }} - ${{ matrix.arch }}"
 
@@ -73,8 +73,8 @@ jobs:
           echo "::endgroup::"
         shell: bash
 
-      # 3. Extract ARCHIVE_FINAL_PATH_NAME from filename.txt
-      - name: 3. Extract ARCHIVE_FINAL_PATH_NAME from filename.txt
+      # (3) - Extract ARCHIVE_FINAL_PATH_NAME from filename.txt
+      - name: (3) - Extract ARCHIVE_FINAL_PATH_NAME from filename.txt
         run: |
           echo "::group::Extract ARCHIVE_FINAL_PATH_NAME"
 
@@ -91,8 +91,49 @@ jobs:
           echo "::endgroup::"
         shell: bash
 
-      # 4a. Upload artifact to GitHub repos with API (Linux/macOS)
-      - name: 4a. Upload artifact to GitHub repos with API (Linux/macOS)
+      # (4) - Update README.md in prod repo with API
+      - name: (4) - Update README.md in prod repo with API
+        if: runner.os != 'Windows'
+        run: |
+          FILE_TO_ADD=README.md
+          echo "Uploading file '${FILE_TO_ADD}' to prod repository..."
+          # Encode Artifact to Base64 (Linux/macOS)
+          cat ${FILE_TO_ADD} | base64 | tr -d '\n' > artifact_base64.txt
+          # Leer el contenido codificado en base64 desde el archivo
+          BASE64_ARTIFACT=$(cat artifact_base64.txt)
+          # Parameters
+          COMMIT_MESSAGE="Added from GitHub Actions"
+          REPOS=("OrganizeTakeoutPhotos")
+          for REPO in "${REPOS[@]}"; do
+            echo "Uploading to $REPO..."
+            URL=https://api.github.com/repos/jaimetur/$REPO/contents/${FILE_TO_ADD} 
+            # Extraer SHA si el archivo existe
+            command="curl -s -f -H 'Authorization: token ${{ secrets.GH_PAT }}' '${URL}' | grep '\"sha\"' | awk -F '\"' '{print \$4}' || echo \"\""
+            # echo "Command: ${command}"
+            SHA=$(eval ${command})
+            echo "SHA: ${SHA}"
+            # Crear archivo temporal para el payload
+            PAYLOAD_FILE=$(mktemp)
+            # Generar el contenido del JSON y guardarlo en el archivo temporal
+            echo "{
+              \"message\": \"${COMMIT_MESSAGE}\",
+              \"content\": \"${BASE64_ARTIFACT}\",
+              \"branch\": \"main\",
+              \"sha\": \"${SHA}\"
+            }" > ${PAYLOAD_FILE}
+            # Subir el archivo (crear o sobrescribir)
+            curl -X PUT \
+                -H "Authorization: token ${{ secrets.GH_PAT }}" \
+                -H "Content-Type: application/json" \
+                -d @${PAYLOAD_FILE} \
+                ${URL}
+            # Limpiar el archivo temporal
+            rm ${PAYLOAD_FILE}
+          done
+        shell: bash
+
+      # (5a) - Upload artifact to GitHub repos with API (Linux/macOS)
+      - name: (5a) - Upload artifact to GitHub repos with API (Linux/macOS)
         if: runner.os != 'Windows'
         run: |
           FILE_TO_ADD=${{ env.ARCHIVE_FINAL_PATH_NAME }}
@@ -132,8 +173,8 @@ jobs:
           done
         shell: bash
 
-      # 4b. Upload artifact to GitHub repos with API (Windows)
-      - name: 4b. Upload artifact to GitHub repos with API (Windows)
+      # (5b) - Upload artifact to GitHub repos with API (Windows)
+      - name: (5b) - Upload artifact to GitHub repos with API (Windows)
         if: runner.os == 'Windows'
         run: |
           $FILE_TO_ADD = $env:ARCHIVE_FINAL_PATH_NAME
@@ -174,6 +215,49 @@ jobs:
           }
         shell: pwsh
 
+      # (6a) - Cleanup (Linux/macOS)
+      - name: (6a) - Cleanup (Linux/macOS)
+        if: runner.os != 'Windows'
+        run: |
+          if [ -f artifact_base64.txt ]; then
+            rm artifact_base64.txt
+            echo "Archivo artifact_base64.txt eliminado de carpeta raiz."
+          elif [ -f src/artifact_base64.txt ]; then
+            rm artifact_base64.txt
+            echo "Archivo artifact_base64.txt eliminado de src."
+          fi
+          if [ -f ${{ env.ARCHIVE_FINAL_PATH_NAME }} ]; then
+            rm ${{ env.ARCHIVE_FINAL_PATH_NAME }}
+            echo "Archivo '${{ env.ARCHIVE_FINAL_PATH_NAME }}' eliminado de carpeta raiz."
+          elif [ -f src/${{ env.ARCHIVE_FINAL_PATH_NAME }} ]; then
+            rm ${{ env.ARCHIVE_FINAL_PATH_NAME }}
+            echo "Archivo '${{ env.ARCHIVE_FINAL_PATH_NAME }}' eliminado de carpeta raiz."
+          fi
+        shell: bash
+
+      # (6b) - Cleanup (Windows)
+      - name: (6b) - Cleanup (Windows)
+        if: runner.os == 'Windows'
+        run: |
+          if (Test-Path "artifact_base64.txt") {
+            Remove-Item -Path "artifact_base64.txt"
+            Write-Host "Archivo artifact_base64.txt eliminado de carpeta raiz."
+          } 
+          elseif (Test-Path "src\artifact_base64.txt") {
+            Remove-Item -Path "src\artifact_base64.txt"
+            Write-Host "Archivo artifact_base64.txt eliminado de carpeta src\."
+          }
+          if (Test-Path "${{ env.ARCHIVE_FINAL_PATH_NAME }}") {
+            Remove-Item -Path "${{ env.ARCHIVE_FINAL_PATH_NAME }}"
+            Write-Host "Archivo '${{ env.ARCHIVE_FINAL_PATH_NAME }}' eliminado de carpeta raiz."
+          } 
+          elseif (Test-Path "src\${{ env.ARCHIVE_FINAL_PATH_NAME }}") {
+            Remove-Item -Path "src\${{ env.ARCHIVE_FINAL_PATH_NAME }}"
+            Write-Host "Archivo '${{ env.ARCHIVE_FINAL_PATH_NAME }}' eliminado de carpeta src\."
+          }
+        shell: pwsh
+
+
 #      # Upload artifact to GitHub repos with CLI (Cross-Platform)
 #      - name: Upload artifact to GitHub repos with CLI (Cross-Platform)
 #        run: |
@@ -209,89 +293,6 @@ jobs:
 #            # Forzar el push (sobrescribe si es necesario)
 #            git push origin ${{ github.ref_name }} --force
 #          done
-
-      # 5. Update README.md in prod repo with API
-      - name: 5. Update README.md in prod repo with API
-        if: runner.os != 'Windows'
-        run: |
-          FILE_TO_ADD=README.md
-          echo "Uploading file '${FILE_TO_ADD}' to prod repository..."
-          # Encode Artifact to Base64 (Linux/macOS)
-          cat ${FILE_TO_ADD} | base64 | tr -d '\n' > artifact_base64.txt
-          # Leer el contenido codificado en base64 desde el archivo
-          BASE64_ARTIFACT=$(cat artifact_base64.txt)
-          # Parameters
-          COMMIT_MESSAGE="Added from GitHub Actions"
-          REPOS=("OrganizeTakeoutPhotos")
-          for REPO in "${REPOS[@]}"; do
-            echo "Uploading to $REPO..."
-            URL=https://api.github.com/repos/jaimetur/$REPO/contents/${FILE_TO_ADD} 
-            # Extraer SHA si el archivo existe
-            command="curl -s -f -H 'Authorization: token ${{ secrets.GH_PAT }}' '${URL}' | grep '\"sha\"' | awk -F '\"' '{print \$4}' || echo \"\""
-            # echo "Command: ${command}"
-            SHA=$(eval ${command})
-            echo "SHA: ${SHA}"
-            # Crear archivo temporal para el payload
-            PAYLOAD_FILE=$(mktemp)
-            # Generar el contenido del JSON y guardarlo en el archivo temporal
-            echo "{
-              \"message\": \"${COMMIT_MESSAGE}\",
-              \"content\": \"${BASE64_ARTIFACT}\",
-              \"branch\": \"main\",
-              \"sha\": \"${SHA}\"
-            }" > ${PAYLOAD_FILE}
-            # Subir el archivo (crear o sobrescribir)
-            curl -X PUT \
-                -H "Authorization: token ${{ secrets.GH_PAT }}" \
-                -H "Content-Type: application/json" \
-                -d @${PAYLOAD_FILE} \
-                ${URL}
-            # Limpiar el archivo temporal
-            rm ${PAYLOAD_FILE}
-          done
-        shell: bash
-
-      # 6a. Cleanup (Linux/macOS)
-      - name: 6a. Cleanup (Linux/macOS)
-        if: runner.os != 'Windows'
-        run: |
-          if [ -f artifact_base64.txt ]; then
-            rm artifact_base64.txt
-            echo "Archivo artifact_base64.txt eliminado de carpeta raiz."
-          elif [ -f src/artifact_base64.txt ]; then
-            rm artifact_base64.txt
-            echo "Archivo artifact_base64.txt eliminado de src."
-          fi
-          if [ -f ${{ env.ARCHIVE_FINAL_PATH_NAME }} ]; then
-            rm ${{ env.ARCHIVE_FINAL_PATH_NAME }}
-            echo "Archivo '${{ env.ARCHIVE_FINAL_PATH_NAME }}' eliminado de carpeta raiz."
-          elif [ -f src/${{ env.ARCHIVE_FINAL_PATH_NAME }} ]; then
-            rm ${{ env.ARCHIVE_FINAL_PATH_NAME }}
-            echo "Archivo '${{ env.ARCHIVE_FINAL_PATH_NAME }}' eliminado de carpeta raiz."
-          fi
-        shell: bash
-
-      # 6b. Cleanup (Windows)
-      - name: 6b. Cleanup (Windows)
-        if: runner.os == 'Windows'
-        run: |
-          if (Test-Path "artifact_base64.txt") {
-            Remove-Item -Path "artifact_base64.txt"
-            Write-Host "Archivo artifact_base64.txt eliminado de carpeta raiz."
-          } 
-          elseif (Test-Path "src\artifact_base64.txt") {
-            Remove-Item -Path "src\artifact_base64.txt"
-            Write-Host "Archivo artifact_base64.txt eliminado de carpeta src\."
-          }
-          if (Test-Path "${{ env.ARCHIVE_FINAL_PATH_NAME }}") {
-            Remove-Item -Path "${{ env.ARCHIVE_FINAL_PATH_NAME }}"
-            Write-Host "Archivo '${{ env.ARCHIVE_FINAL_PATH_NAME }}' eliminado de carpeta raiz."
-          } 
-          elseif (Test-Path "src\${{ env.ARCHIVE_FINAL_PATH_NAME }}") {
-            Remove-Item -Path "src\${{ env.ARCHIVE_FINAL_PATH_NAME }}"
-            Write-Host "Archivo '${{ env.ARCHIVE_FINAL_PATH_NAME }}' eliminado de carpeta src\."
-          }
-        shell: pwsh
 
 #      # Upload the compiled compressed file to the Actions task
 #      - name: Archive Artifacts
